language: python
sudo: false

python:
  - "2.7"
  - "pypy"
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7-dev"

install:
  - pip install tox

script:
  - tox -e $(tox -l | grep py$(echo $TRAVIS_PYTHON_VERSION | sed -e 's/pypypy/pypy/g') | tr '\n' ',')
